// =============================================
// data.js — Barcha ma'lumotlar (notes, subjects)
// =============================================

const NOTES = [
  {
    id: 1,
    title: "Integral hisob konspekti",
    subject: "Matematika",
    desc: "Aniq va noaniq integrallar, hisoblash usullari va misollar bilan.",
    author: "Dilnoza T.",
    date: "2025-01-10",
    likes: 142,
    downloads: 890,
    rating: 4.9,
    badge: "badge-math",
  },
  {
    id: 2,
    title: "Kvant mexanikasi asoslari",
    subject: "Fizika",
    desc: "To'lqin funksiyasi, Shredinger tenglamasi va kvant holatlari.",
    author: "Sardor A.",
    date: "2025-01-08",
    likes: 98,
    downloads: 654,
    rating: 4.7,
    badge: "badge-physics",
  },
  {
    id: 3,
    title: "O'rta asrlar Yevropa tarixi",
    subject: "Tarix",
    desc: "Feodalizm, Salib yurishlari va Renessans davrining qisqacha xulosasi.",
    author: "Malika R.",
    date: "2025-01-05",
    likes: 76,
    downloads: 423,
    rating: 4.5,
    badge: "badge-history",
  },
  {
    id: 4,
    title: "Python dasturlash asoslari",
    subject: "Dasturlash",
    desc: "O'zgaruvchilar, sikllar, funksiyalar va OOP — boshlang'ichlar uchun.",
    author: "Jasur K.",
    date: "2025-01-12",
    likes: 201,
    downloads: 1240,
    rating: 5.0,
    badge: "badge-cs",
  },
  {
    id: 5,
    title: "Organik kimyo formulalar",
    subject: "Kimyo",
    desc: "Asosiy organik birikmalar, reaksiyalar va nomenklatura.",
    author: "Zulfiya M.",
    date: "2025-01-03",
    likes: 55,
    downloads: 312,
    rating: 4.3,
    badge: "badge-chemistry",
  },
  {
    id: 6,
    title: "Differensial tenglamalar",
    subject: "Matematika",
    desc: "1-chi va 2-chi tartibli tenglamalar, yechish metodlari.",
    author: "Bobur N.",
    date: "2024-12-28",
    likes: 89,
    downloads: 567,
    rating: 4.6,
    badge: "badge-math",
  },
  {
    id: 7,
    title: "Elektrodinamika qisqacha",
    subject: "Fizika",
    desc: "Maksvell tenglamalari, elektr maydoni va magnit induksiyasi.",
    author: "Kamola S.",
    date: "2024-12-25",
    likes: 67,
    downloads: 389,
    rating: 4.4,
    badge: "badge-physics",
  },
  {
    id: 8,
    title: "React.js boshlovchilar uchun",
    subject: "Dasturlash",
    desc: "Komponentlar, hooks, state management — amaliy misollar bilan.",
    author: "Sherzod I.",
    date: "2025-01-15",
    likes: 187,
    downloads: 1089,
    rating: 4.8,
    badge: "badge-cs",
  },
];

const SUBJECTS = [
  { emoji: "➕", name: "Matematika",       count: 342 },
  { emoji: "⚛️", name: "Fizika",           count: 218 },
  { emoji: "📜", name: "Tarix",            count: 195 },
  { emoji: "💻", name: "Dasturlash",       count: 287 },
  { emoji: "🧪", name: "Kimyo",            count: 143 },
  { emoji: "🌿", name: "Biologiya",        count: 167 },
  { emoji: "🇬🇧", name: "Ingliz tili",    count: 231 },
  { emoji: "📈", name: "Iqtisodiyot",      count: 112 },
  { emoji: "🎨", name: "San'at",           count: 88  },
  { emoji: "🏃", name: "Jismoniy tarbiya", count: 54  },
  { emoji: "🔭", name: "Astronomiya",      count: 76  },
  { emoji: "📐", name: "Geometriya",       count: 134 },
];

// Avatar ranglari
const AVATAR_COLORS = [
  "#f0c040", "#e07b3f", "#60a5fa",
  "#4ade80", "#c084fc", "#f87171",
  "#fb923c", "#34d399",
];
